# .github/workflows/web-ci.yml
name: Build Apache Web Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Decode GCP service account key
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > key.json

    - name: Login to GCR
      run: |
        gcloud auth activate-service-account --key-file=key.json
        gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ay-repo/web:1.0